# Generated by Django 3.0.5 on 2020-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='page1/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoru',
            field=models.CharField(default='', max_length=50),
        ),
    ]
