# Generated by Django 3.0.5 on 2020-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
