# Generated by Django 3.0.5 on 2020-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0005_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default='0'),
        ),
    ]
