# Generated by Django 3.0.5 on 2020-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0006_auto_20200523_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='client_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
