# Generated by Django 3.0.5 on 2020-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0007_product_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(default='0')),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
