# Generated by Django 3.0.5 on 2020-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0008_auto_20200526_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
