# Generated by Django 3.0.5 on 2020-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0009_auto_20200526_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
